package org.campware.cream.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.turbine.om.Retrievable;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Fri Jan 26 03:28:50 CET 2007]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to ContactCategory
 */
public abstract class BaseContactCategory extends BaseObject
    implements org.apache.turbine.om.Retrievable
{
    /** The Peer class */
    private static final ContactCategoryPeer peer =
        new ContactCategoryPeer();

        
    /** The value for the contactCatId field */
    private int contactCatId;
      
    /** The value for the contactCatName field */
    private String contactCatName;
  
    
    /**
     * Get the ContactCatId
     *
     * @return int
     */
    public int getContactCatId()
    {
        return contactCatId;
    }

                                              
    /**
     * Set the value of ContactCatId
     *
     * @param v new value
     */
    public void setContactCatId(int v) throws TorqueException
    {
    
                  if (this.contactCatId != v)
              {
            this.contactCatId = v;
            setModified(true);
        }
    
          
                                  
                  // update associated Contact
        if (collContacts != null)
        {
            for (int i = 0; i < collContacts.size(); i++)
            {
                ((Contact) collContacts.get(i))
                    .setContactCatId(v);
            }
        }
                                }
  
    /**
     * Get the ContactCatName
     *
     * @return String
     */
    public String getContactCatName()
    {
        return contactCatName;
    }

                        
    /**
     * Set the value of ContactCatName
     *
     * @param v new value
     */
    public void setContactCatName(String v) 
    {
    
                  if (!ObjectUtils.equals(this.contactCatName, v))
              {
            this.contactCatName = v;
            setModified(true);
        }
    
          
              }
  
         
                                
            
          /**
     * Collection to store aggregation of collContacts
     */
    protected List collContacts;

    /**
     * Temporary storage of collContacts to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initContacts()
    {
        if (collContacts == null)
        {
            collContacts = new ArrayList();
        }
    }

    /**
     * Method called to associate a Contact object to this object
     * through the Contact foreign key attribute
     *
     * @param l Contact
     * @throws TorqueException
     */
    public void addContact(Contact l) throws TorqueException
    {
        getContacts().add(l);
        l.setContactCategory((ContactCategory) this);
    }

    /**
     * The criteria used to select the current contents of collContacts
     */
    private Criteria lastContactsCriteria = null;
      
    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getContacts(new Criteria())
     *
     * @throws TorqueException
     */
    public List getContacts() throws TorqueException
    {
              if (collContacts == null)
        {
            collContacts = getContacts(new Criteria(10));
        }
        return collContacts;
          }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     * If this ContactCategory is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getContacts(Criteria criteria) throws TorqueException
    {
              if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                        criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId() );
                        collContacts = ContactPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                            criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                            if (!lastContactsCriteria.equals(criteria))
                {
                    collContacts = ContactPeer.doSelect(criteria);
                }
            }
        }
        lastContactsCriteria = criteria;

        return collContacts;
          }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getContacts(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getContacts(Connection con) throws TorqueException
    {
              if (collContacts == null)
        {
            collContacts = getContacts(new Criteria(10), con);
        }
        return collContacts;
          }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     * If this ContactCategory is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getContacts(Criteria criteria, Connection con)
            throws TorqueException
    {
              if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                         criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                         collContacts = ContactPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                              criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                             if (!lastContactsCriteria.equals(criteria))
                 {
                     collContacts = ContactPeer.doSelect(criteria, con);
                 }
             }
         }
         lastContactsCriteria = criteria;

         return collContacts;
           }

                                                                  
              
                    
                    
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory is new, it will return
     * an empty collection; or if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContactCategory.
     */
    protected List getContactsJoinCustomer(Criteria criteria)
        throws TorqueException
    {
                    if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                              criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                              collContacts = ContactPeer.doSelectJoinCustomer(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            
                        criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                                    if (!lastContactsCriteria.equals(criteria))
            {
                collContacts = ContactPeer.doSelectJoinCustomer(criteria);
            }
        }
        lastContactsCriteria = criteria;

        return collContacts;
                }
                  
                    
                    
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory is new, it will return
     * an empty collection; or if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContactCategory.
     */
    protected List getContactsJoinSalutation(Criteria criteria)
        throws TorqueException
    {
                    if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                              criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                              collContacts = ContactPeer.doSelectJoinSalutation(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            
                        criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                                    if (!lastContactsCriteria.equals(criteria))
            {
                collContacts = ContactPeer.doSelectJoinSalutation(criteria);
            }
        }
        lastContactsCriteria = criteria;

        return collContacts;
                }
                  
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory is new, it will return
     * an empty collection; or if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContactCategory.
     */
    protected List getContactsJoinContactCategory(Criteria criteria)
        throws TorqueException
    {
                    if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                              criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                              collContacts = ContactPeer.doSelectJoinContactCategory(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            
                        criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                                    if (!lastContactsCriteria.equals(criteria))
            {
                collContacts = ContactPeer.doSelectJoinContactCategory(criteria);
            }
        }
        lastContactsCriteria = criteria;

        return collContacts;
                }
                  
                    
                    
                                            
                                                                          
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory is new, it will return
     * an empty collection; or if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContactCategory.
     */
    protected List getContactsJoinCountryRelatedByCountryId(Criteria criteria)
        throws TorqueException
    {
                    if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                              criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                              collContacts = ContactPeer.doSelectJoinCountryRelatedByCountryId(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            
                        criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                                    if (!lastContactsCriteria.equals(criteria))
            {
                collContacts = ContactPeer.doSelectJoinCountryRelatedByCountryId(criteria);
            }
        }
        lastContactsCriteria = criteria;

        return collContacts;
                }
                  
                    
                    
                                            
                                                                          
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory is new, it will return
     * an empty collection; or if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContactCategory.
     */
    protected List getContactsJoinRegionRelatedByRegionId(Criteria criteria)
        throws TorqueException
    {
                    if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                              criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                              collContacts = ContactPeer.doSelectJoinRegionRelatedByRegionId(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            
                        criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                                    if (!lastContactsCriteria.equals(criteria))
            {
                collContacts = ContactPeer.doSelectJoinRegionRelatedByRegionId(criteria);
            }
        }
        lastContactsCriteria = criteria;

        return collContacts;
                }
                  
                    
                    
                                            
                                                                          
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory is new, it will return
     * an empty collection; or if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContactCategory.
     */
    protected List getContactsJoinCountryRelatedBySecCountryId(Criteria criteria)
        throws TorqueException
    {
                    if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                              criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                              collContacts = ContactPeer.doSelectJoinCountryRelatedBySecCountryId(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            
                        criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                                    if (!lastContactsCriteria.equals(criteria))
            {
                collContacts = ContactPeer.doSelectJoinCountryRelatedBySecCountryId(criteria);
            }
        }
        lastContactsCriteria = criteria;

        return collContacts;
                }
                  
                    
                    
                                            
                                                                          
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory is new, it will return
     * an empty collection; or if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContactCategory.
     */
    protected List getContactsJoinRegionRelatedBySecRegionId(Criteria criteria)
        throws TorqueException
    {
                    if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                              criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                              collContacts = ContactPeer.doSelectJoinRegionRelatedBySecRegionId(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            
                        criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                                    if (!lastContactsCriteria.equals(criteria))
            {
                collContacts = ContactPeer.doSelectJoinRegionRelatedBySecRegionId(criteria);
            }
        }
        lastContactsCriteria = criteria;

        return collContacts;
                }
                  
                    
                    
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory is new, it will return
     * an empty collection; or if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContactCategory.
     */
    protected List getContactsJoinLanguage(Criteria criteria)
        throws TorqueException
    {
                    if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                              criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                              collContacts = ContactPeer.doSelectJoinLanguage(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            
                        criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                                    if (!lastContactsCriteria.equals(criteria))
            {
                collContacts = ContactPeer.doSelectJoinLanguage(criteria);
            }
        }
        lastContactsCriteria = criteria;

        return collContacts;
                }
                  
                    
                    
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContactCategory is new, it will return
     * an empty collection; or if this ContactCategory has previously
     * been saved, it will retrieve related Contacts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContactCategory.
     */
    protected List getContactsJoinJobPosition(Criteria criteria)
        throws TorqueException
    {
                    if (collContacts == null)
        {
            if (isNew())
            {
               collContacts = new ArrayList();
            }
            else
            {
                              criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                              collContacts = ContactPeer.doSelectJoinJobPosition(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            
                        criteria.add(ContactPeer.CONTACT_CAT_ID, getContactCatId());
                                    if (!lastContactsCriteria.equals(criteria))
            {
                collContacts = ContactPeer.doSelectJoinJobPosition(criteria);
            }
        }
        lastContactsCriteria = criteria;

        return collContacts;
                }
                            


          
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("ContactCatId");
              fieldNames.add("ContactCatName");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("ContactCatId"))
        {
                return new Integer(getContactCatId());
            }
          if (name.equals("ContactCatName"))
        {
                return getContactCatName();
            }
          return null;
    }
    
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(ContactCategoryPeer.CONTACT_CAT_ID))
        {
                return new Integer(getContactCatId());
            }
          if (name.equals(ContactCategoryPeer.CONTACT_CAT_NAME))
        {
                return getContactCatName();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getContactCatId());
            }
              if (pos == 1)
        {
                return getContactCatName();
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(ContactCategoryPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    ContactCategoryPeer.doInsert((ContactCategory) this, con);
                    setNew(false);
                }
                else
                {
                    ContactCategoryPeer.doUpdate((ContactCategory) this, con);
                }
            }

                                      
                
                    if (collContacts != null)
            {
                for (int i = 0; i < collContacts.size(); i++)
                {
                    ((Contact) collContacts.get(i)).save(con);
                }
            }
                                  alreadyInSave = false;
        }
      }

                        
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key contactCatId ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
            setContactCatId(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
            setContactCatId(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getContactCatId());
      }
 
    /**
     * get an id that differentiates this object from others
     * of its class.
     */
    public String getQueryKey()
    {
        if (getPrimaryKey() == null)
        {
            return "";
        }
        else
        {
            return getPrimaryKey().toString();
        }
    }

    /**
     * set an id that differentiates this object from others
     * of its class.
     */
    public void setQueryKey(String key)
        throws TorqueException
    {
        setPrimaryKey(key);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public ContactCategory copy() throws TorqueException
    {
        return copyInto(new ContactCategory());
    }
  
    protected ContactCategory copyInto(ContactCategory copyObj) throws TorqueException
    {
          copyObj.setContactCatId(contactCatId);
          copyObj.setContactCatName(contactCatName);
  
                            copyObj.setContactCatId( 0);
                  
                                      
                            
        List v = getContacts();
        for (int i = 0; i < v.size(); i++)
        {
            Contact obj = (Contact) v.get(i);
            copyObj.addContact(obj.copy());
        }
                            return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public ContactCategoryPeer getPeer()
    {
        return peer;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("ContactCategory:\n");
        str.append("ContactCatId = ")
               .append(getContactCatId())
             .append("\n");
        str.append("ContactCatName = ")
               .append(getContactCatName())
             .append("\n");
        return(str.toString());
    }
}
