
package org.campware.cream.om;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue May 03 03:16:57 CEST 2005]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class NewsSubscription
    extends org.campware.cream.om.BaseNewsSubscription
    implements Persistent
{
}
