
package org.campware.cream.om;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 25 22:39:31 CET 2005]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Product
    extends org.campware.cream.om.BaseProduct
    implements Persistent
{
}
