package org.campware.cream.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Fri Jan 26 03:28:50 CET 2007]
  *
  */
public class ProductMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.campware.cream.om.map.ProductMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("cream");

        dbMap.addTable("PRODUCT");
        TableMap tMap = dbMap.getTable("PRODUCT");

        tMap.setPrimaryKeyMethod(TableMap.NATIVE);


              tMap.addPrimaryKey("PRODUCT.PRODUCT_ID", new Integer(0));
                    tMap.addColumn("PRODUCT.PRODUCT_CODE", "");
                    tMap.addColumn("PRODUCT.STATUS", new Integer(0));
                    tMap.addColumn("PRODUCT.PRIORITY", new Integer(0));
                    tMap.addColumn("PRODUCT.PRODUCT_TYPE", new Integer(0));
                    tMap.addForeignKey(
                "PRODUCT.PRODUCT_CAT_ID", new Integer(0) , "PRODUCT_CATEGORY" ,
                "PRODUCT_CAT_ID");
                    tMap.addColumn("PRODUCT.PRODUCT_DESCRIPTION", "");
                    tMap.addColumn("PRODUCT.PRODUCT_DISPLAY", "");
                    tMap.addColumn("PRODUCT.BASE_PRICE", new Double(0));
                    tMap.addForeignKey(
                "PRODUCT.UOM_ID", new Integer(0) , "UOM" ,
                "UOM_ID");
                    tMap.addColumn("PRODUCT.WEB_URL", "");
                    tMap.addColumn("PRODUCT.SHOW_ON_PRICELIST", new Integer(0));
                    tMap.addForeignKey(
                "PRODUCT.VENDOR_ID", new Integer(0) , "VENDOR" ,
                "VENDOR_ID");
                    tMap.addColumn("PRODUCT.VENDORS_CODE", "");
                    tMap.addColumn("PRODUCT.EAN_UPC_CODE", "");
                    tMap.addColumn("PRODUCT.LOCATION", "");
                    tMap.addColumn("PRODUCT.CUSTOM_1", "");
                    tMap.addColumn("PRODUCT.CUSTOM_2", "");
                    tMap.addColumn("PRODUCT.CUSTOM_3", "");
                    tMap.addColumn("PRODUCT.CUSTOM_4", "");
                    tMap.addColumn("PRODUCT.CUSTOM_5", "");
                    tMap.addColumn("PRODUCT.CUSTOM_6", "");
                    tMap.addColumn("PRODUCT.NOTES", "");
                    tMap.addColumn("PRODUCT.CREATED", new Date());
                    tMap.addColumn("PRODUCT.MODIFIED", new Date());
                    tMap.addColumn("PRODUCT.CREATED_BY", "");
                    tMap.addColumn("PRODUCT.MODIFIED_BY", "");
          }
}
