package org.campware.cream.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Fri Jan 26 03:28:50 CET 2007]
  *
  */
public class TaskMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.campware.cream.om.map.TaskMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("cream");

        dbMap.addTable("TASK");
        TableMap tMap = dbMap.getTable("TASK");

        tMap.setPrimaryKeyMethod(TableMap.NATIVE);


              tMap.addPrimaryKey("TASK.TASK_ID", new Integer(0));
                    tMap.addColumn("TASK.TASK_CODE", "");
                    tMap.addColumn("TASK.STATUS", new Integer(0));
                    tMap.addColumn("TASK.PRIORITY", new Integer(0));
                    tMap.addColumn("TASK.START_DATE", new Date());
                    tMap.addColumn("TASK.DUE_DATE", new Date());
                    tMap.addColumn("TASK.PROGRESS", new Integer(0));
                    tMap.addForeignKey(
                "TASK.CUSTOMER_ID", new Integer(0) , "CUSTOMER" ,
                "CUSTOMER_ID");
                    tMap.addForeignKey(
                "TASK.CONTACT_ID", new Integer(0) , "CONTACT" ,
                "CONTACT_ID");
                    tMap.addForeignKey(
                "TASK.PRODUCT_ID", new Integer(0) , "PRODUCT" ,
                "PRODUCT_ID");
                    tMap.addForeignKey(
                "TASK.PROJECT_ID", new Integer(0) , "PROJECT" ,
                "PROJECT_ID");
                    tMap.addColumn("TASK.ACCESS", new Integer(0));
                    tMap.addColumn("TASK.ASSIGNED_TO", "");
                    tMap.addColumn("TASK.SUBJECT", "");
                    tMap.addColumn("TASK.DESCRIPTION", "");
                    tMap.addColumn("TASK.CREATED", new Date());
                    tMap.addColumn("TASK.MODIFIED", new Date());
                    tMap.addColumn("TASK.CREATED_BY", "");
                    tMap.addColumn("TASK.MODIFIED_BY", "");
          }
}
